## Exploring Students Performance Bootcamp Day - 1 (Data Engineering and Gen AI on cloud )

In [2]:
#Import the necessary libraries :

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Read the dataset :

df=pd.read_csv("/content/student_performance.csv")

In [4]:
#View all the rows and columns

df

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [5]:
#Acessing top 5 elements
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
#Accessing Bottom 5 elements :

df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [7]:
# To access shapes of Data :

print("Shape of Data :",df.shape)

print("Number of Rows :",df.shape[0])

print("Number of columns :",df.shape[1])

Shape of Data : (30, 13)
Number of Rows : 30
Number of columns : 13

In [8]:
# Printing columns vertically

df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [9]:
#Printting columns horizontally

df.columns

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [10]:
#To understand the data types :

df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [11]:
# To get the staticstical Summary

df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [12]:
# To check the null values :

df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [13]:
# Acessing a specific column

df['city'].head()

0       Mumbai
1    Ahmedabad
2        Delhi
3    Hyderabad
4        Kochi
Name: city, dtype: object

In [14]:
#printing students data whose math_score is > than 90

df[df['math_score']>90]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [15]:
# Viewing unique departments

df['department'].unique()

array(['Computer Science', 'Electronics', 'Mechanical', 'Civil'],
      dtype=object)

In [16]:
#accessing specific column values with it's count
df['department'].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [17]:
#Filtering and conditional Selection

cs_stud = df[df['department']=='Computer Science']

print(len(cs_stud))

13

In [18]:
#Calculating the total score :

df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']

df['total_score'].head()

0    326
1    325
2    255
3    273
4    356
Name: total_score, dtype: int64

In [19]:
# Find the mean of the department using the group by function

dept_avg=df.groupby('department')['total_score'].mean().round(2)

In [20]:
dept_avg

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [21]:
#Sort the students by the total score

df_sorted=df.sort_values(by='total_score',ascending=False).head(10)
print("Top 10 studens by total score")
df_sorted

Top 10 studens by total score

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,371
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,367
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,365
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023,356
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023,354
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023,336
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023,334
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023,327
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326

## Practice Questions


1. How many students are from the electronics Department ?
2. What is the average attendence of Female Students ?
3. Who is the student with lowest programming score ?
4. How many students scored above 80 in math ?
5. What is the average total_score for students with attendence above 90% ?

In [22]:
# Total students from Electronics department

total_ECE_stud = df['department'].value_counts()['Electronics']

print(f"Number of students in the Electronics Department: {total_ECE_stud}")

Number of students in the Electronics Department: 6

In [23]:
# Average Attendence of Female Students

Avg_fem_stud=df[df['gender']=='Female']['attendance_percentage'].mean().round(2)
print("Average Attendence of Female Students ",Avg_fem_stud)

Average Attendence of Female Students  88.53

In [24]:
#Student with Lowest Programming Score

low_prog_score = df.loc[df['programming_score'].idxmin()]['name']
print("Student with lowest Programming score : ",low_prog_score)

Student with lowest Programming score :  Manoj Pandey

In [25]:
# Students scored 80 above on math

math_score_above80 = df[df['math_score']>80]['name'].count()

math_score_above80

np.int64(11)

In [26]:
# Average total score of srudents with attendence above 90 %

avg_total_score = df[df['attendance_percentage']>90]['total_score'].mean().round(2)

avg_total_score

np.float64(335.8)


# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Python to analyze student data and generate a detailed report.

# Dataset Columns:

- name

- gender

- department

- math_score

- programming_score

- attendance_percentage

- total_score

### Tasks to Perform

1. Display Project title
Print a formatted title with seperator Lines

2. Dataset Overview
Display:
- Total number of students
- Total number of columns
- Number of unique departments

3. Department Wise Analysis
Display the count of students in each department

4. Score Analysis
Find and display:
- Highest math score
- Lowest math score
- Average math score
- Average programming score
- Average attendence percentage

5. Gender wise analysis
Calculate and display average total score grouped by gender.

6. Top Performers
Show:
- Student name
- Department
- Total score

7. Attendence Analysis
Display:
- Name
- Department
- Attendence percentage
If all students have attendence above 75%
Print a suitable message


# Concepts to use
- pandas,Dataframe,groupby(),value_counts(),mean(),max(),min() and suitable methods

In [27]:
# Printing the Project title with the seperator Lines :

print("======================== Student Data Explorer ==========================")

======================== Student Data Explorer ==========================

##  Overview of the dataset

In [28]:
# Overview of the dataset

df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,325
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,255
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,273
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356

In [39]:
#Printing the total number of students

print("Total Students : " ,df['student_id'].count())
print()

#Printing total columns

print("Total columns : ",len(df.columns))
print()

#printing number of unique departments

print("Unique departments : ",len(df['department'].unique()))
print()

Total Students :  30

Total columns :  14

Unique departments :  4

## Displaying the count of students in each department

In [40]:
df.groupby('department')['student_id'].count()

department
Civil                5
Computer Science    13
Electronics          6
Mechanical           6
Name: student_id, dtype: int64

## Score Analysis

In [42]:
#Finding highest math score

high_math_score=df['math_score'].max()
print("Highest math score : ",high_math_score)
print()

#Print the lowest math score
low_math_score=df['math_score'].min()
print("Lowest math score :",low_math_score)
print()

#Print the average math score
avg_math_score=df['math_score'].mean().round(2)
print("Average math score :",avg_math_score)
print()

#Print the average programming score
avg_prog_score=df['programming_score'].mean()
print("Average Programming score : ",avg_prog_score)
print()


#Average attendence score
avg_attend_score = df['attendance_percentage'].mean()
print("Average Attendence percentage : ",avg_attend_score)
print()

Highest math score :  95

Lowest math score : 56

Average math score : 76.07

Average Programming score :  67.6

Average Attendence percentage :  84.5

## Calculating and display average total score grouped by gender

In [43]:
df.groupby('gender')['total_score'].mean()

gender
Female    310.666667
Male      280.666667
Name: total_score, dtype: float64

## To display the top performers name, department and total score

In [48]:
#To display the top 3 performers name, department and total score

top_performers = df.nlargest(3, 'total_score')
top_performers[['name','department','total_score']]

              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365

# Attendence Analyis display

In [61]:
#Attenedence analysis

ans=df.groupby('attendance_percentage')['student_id'].count()
print(ans)
print()

if df['attendance_percentage'].all()>75:
  print("All students have more than 75 % of attendence")
else:
  print("Not all students have more than 75 % of attendence")

attendance_percentage
65    1
68    1
70    1
72    1
73    1
74    1
75    1
77    1
78    1
80    1
82    1
83    1
84    1
85    1
86    1
87    2
88    1
89    1
90    1
91    2
92    1
93    1
94    1
95    2
96    1
97    1
98    1
Name: student_id, dtype: int64

Not all students have more than 75 % of attendence